/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formmahasiswa;

/**
 *IF2  RAHMAYUDHI PRAKOSO - 10119051
 *IF2  HANDRIAN RIVALDI - 10119074
 */
public class frm_utama extends javax.swing.JFrame {

    /**
     * 
     */
    public frm_utama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jToolBar1 = new javax.swing.JToolBar();
        btn_mahasiswa = new javax.swing.JButton();
        btn_mataKuliah = new javax.swing.JButton();
        btn_nilai = new javax.swing.JButton();
        btn_nilaiakhir = new javax.swing.JButton();
        btn_simulasiKasus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btn_mahasiswa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_mahasiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formmahasiswa/mahasiswa.png"))); // NOI18N
        btn_mahasiswa.setText("Data Mahasiswa");
        btn_mahasiswa.setFocusable(false);
        btn_mahasiswa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_mahasiswa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_mahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mahasiswaActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_mahasiswa);

        btn_mataKuliah.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_mataKuliah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formmahasiswa/mata_kuliah.png"))); // NOI18N
        btn_mataKuliah.setText("Data Mata Kuliah");
        btn_mataKuliah.setFocusable(false);
        btn_mataKuliah.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_mataKuliah.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_mataKuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mataKuliahActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_mataKuliah);

        btn_nilai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_nilai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formmahasiswa/nilai.png"))); // NOI18N
        btn_nilai.setText("Data Nilai");
        btn_nilai.setFocusable(false);
        btn_nilai.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_nilai.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_nilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nilaiActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_nilai);

        btn_nilaiakhir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_nilaiakhir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formmahasiswa/nilai Akhir.png"))); // NOI18N
        btn_nilaiakhir.setText("Simulasi Nilai Akhir");
        btn_nilaiakhir.setFocusable(false);
        btn_nilaiakhir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_nilaiakhir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_nilaiakhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nilaiakhirActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_nilaiakhir);

        btn_simulasiKasus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_simulasiKasus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formmahasiswa/simulasinilai.png"))); // NOI18N
        btn_simulasiKasus.setText("Simulasi Kasus");
        btn_simulasiKasus.setFocusable(false);
        btn_simulasiKasus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_simulasiKasus.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_simulasiKasus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simulasiKasusActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_simulasiKasus);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formmahasiswa/handriann.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(18, 18, 18, 18, new java.awt.Color(0, 0, 0)));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formmahasiswa/ydhii.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(20, 20, 20, 20, new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("10119074 - HANDRIAN RIVALDI");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("10119051 - RAHMAYUDHI PRAKOSO");

        jMenu1.setText("Aplikasi Kemahasiswaan");

        jMenuItem1.setText("Tentang Pembuat");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(0, 88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mahasiswaActionPerformed
        // TODO add your handling code here:
        frm_mhs mhs = new frm_mhs();
        mhs.setVisible(true);
        
        //Menghilangkan form utama
        this.setVisible(false);
    }//GEN-LAST:event_btn_mahasiswaActionPerformed

    private void btn_mataKuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mataKuliahActionPerformed
        // TODO add your handling code here:
        frm_matakuliah matkul = new frm_matakuliah();
        matkul.setVisible(true);
        
        //Menghilangkan form utama
        this.setVisible(false);
    }//GEN-LAST:event_btn_mataKuliahActionPerformed

    private void btn_nilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nilaiActionPerformed
        // TODO add your handling code here:
        frm_nilai nilai = new frm_nilai();
        nilai.setVisible(true);
        
        //Menghilangkan form utama
        this.setVisible(false);
    }//GEN-LAST:event_btn_nilaiActionPerformed

    private void btn_nilaiakhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nilaiakhirActionPerformed
        // TODO add your handling code here:
        frm_nilaiAkhir akhir = new frm_nilaiAkhir();
        akhir.setVisible(true);
        
        //Menghilangkan form utama
        this.setVisible(false);
    }//GEN-LAST:event_btn_nilaiakhirActionPerformed

    private void btn_simulasiKasusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simulasiKasusActionPerformed
        // TODO add your handling code here:
        frm_login login = new frm_login();
        login.setVisible(true);
        
        //Menghilangkan form utama
        this.setVisible(false);
        
    }//GEN-LAST:event_btn_simulasiKasusActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        frm_tentangPembuat ttn = new frm_tentangPembuat();
        ttn.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_mahasiswa;
    private javax.swing.JButton btn_mataKuliah;
    private javax.swing.JButton btn_nilai;
    private javax.swing.JButton btn_nilaiakhir;
    private javax.swing.JButton btn_simulasiKasus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
