/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formmahasiswa;

/**
 *
 * @author Acer
 */
public class frm_utama extends javax.swing.JFrame {

    /**
     * Creates new form frm_utama
     */
    public frm_utama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jToolBar1 = new javax.swing.JToolBar();
        btn_dataMahasiswa = new javax.swing.JButton();
        btn_mataKuliah = new javax.swing.JButton();
        btn_nilai = new javax.swing.JButton();
        btn_nilaiAkhir = new javax.swing.JButton();
        btn_simulasiKasus = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btn_dataMahasiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formmahasiswa/mahasiswa.png"))); // NOI18N
        btn_dataMahasiswa.setText("Data Mahasiswa");
        btn_dataMahasiswa.setFocusable(false);
        btn_dataMahasiswa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_dataMahasiswa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_dataMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dataMahasiswaActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_dataMahasiswa);

        btn_mataKuliah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formmahasiswa/mata_kuliah.png"))); // NOI18N
        btn_mataKuliah.setText("Data Mata Kuliah");
        btn_mataKuliah.setFocusable(false);
        btn_mataKuliah.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_mataKuliah.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_mataKuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mataKuliahActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_mataKuliah);

        btn_nilai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formmahasiswa/nilai.png"))); // NOI18N
        btn_nilai.setText("Data Nilai");
        btn_nilai.setFocusable(false);
        btn_nilai.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_nilai.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_nilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nilaiActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_nilai);

        btn_nilaiAkhir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formmahasiswa/nilai Akhir.png"))); // NOI18N
        btn_nilaiAkhir.setText("Simulasi Nilai Akhir");
        btn_nilaiAkhir.setFocusable(false);
        btn_nilaiAkhir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_nilaiAkhir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_nilaiAkhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nilaiAkhirActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_nilaiAkhir);

        btn_simulasiKasus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formmahasiswa/simulasinilai.png"))); // NOI18N
        btn_simulasiKasus.setText("Simulasi Kasus");
        btn_simulasiKasus.setFocusable(false);
        btn_simulasiKasus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_simulasiKasus.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_simulasiKasus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simulasiKasusActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_simulasiKasus);

        jMenu1.setText("Aplikasi Kemahasiswaan");

        jMenuItem1.setText("Tentang Pembuat");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 70, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 382, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void btn_nilaiAkhirActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        frm_nilaiAkhir nAkhir = new frm_nilaiAkhir();
        nAkhir.setVisible(true);
        
        //Menghilangkan form utama
        this.setVisible(false);
        
    }                                              

    private void btn_dataMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        frm_mhs mahasiswa = new frm_mhs();
        mahasiswa.setVisible(true);
        
        //Menghilangkan form utama
        this.setVisible(false);
        
    }                                                 

    private void btn_mataKuliahActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        frm_matakuliah matkul = new frm_matakuliah();
        matkul.setVisible(true);
        
        //Menghilangkan form utama
        this.setVisible(false);
        
    }                                              

    private void btn_nilaiActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        frm_nilai nilai = new frm_nilai();
        nilai.setVisible(true);
        
        //Menghilangkan form utama
        this.setVisible(false);
        
    }                                         

    private void btn_simulasiKasusActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
       
    }                                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btn_dataMahasiswa;
    private javax.swing.JButton btn_mataKuliah;
    private javax.swing.JButton btn_nilai;
    private javax.swing.JButton btn_nilaiAkhir;
    private javax.swing.JButton btn_simulasiKasus;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration                   
}
